export const popular = [
{
  id: 1,
  image: "./manga/popular-01.webp",
  name: "Агуу зүйл бүтээх зам",
  rating: "5/5",
  category: "Адал явдал",
  views: "36",
  color: "#80a3ea",
},
{
  id: 2,
  image: "./manga/popular-02.webp",
  name: "Хаалттай хот",
  rating: "5/5",
  category: "Хайр дурлал",
  views: "28",
  color: "#f12867",
},
{
  id: 3,
  image: "./manga/popular-03.webp",
  name: "Эзэнт гүрний сэнтий",
  rating: "5/5",
  category: "Романтик",
  views: "41",
  color: "#f1de15",
},
{
  id: 4,
  image: "./manga/popular-04.webp",
  name: "Тоглоом дахин давтагдана",
  rating: "5/5",
  category: "Хүчтэн",
  views: "44",
  color: "#37a5b3",
},
];


export const something = [
  {
    id: 1,
    image: "./manga/something-01.webp",
    name: "Шидэт сарнай",
    rating: "5/5",
    category: "Адал явдал",
    views: "36",
    color: "#80a3ea",
  },
  {
    id: 2,
    image: "./manga/something-02.webp",
    name: "Миний таван нэрт дайчдын түүх",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "28",
    color: "#f12867",
  },
  {
    id: 3,
    image: "./manga/something-03.webp",
    name: "Ичгүүргүй илбэчин",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
  {
    id: 4,
    image: "./manga/something-04.webp",
    name: "Тоглоом дахин давтагдана",
    rating: "5/5",
    category: "Хүчтэн",
    views: "44",
    color: "#37a5b3",
  },
  {
    id: 5,
    image: "./manga/something-05.webp",
    name: "Хөрөнгө оруулагч Z! Нөлөөлөл",
    rating: "5/5",
    category: "Тулаант",
    views: "32",
    color: "#54cf17",
  },
  {
    id: 6,
    image: "./manga/something-06.webp",
    name: "Чамтай өнгөрөөсөн сайхан цаг минь",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "26",
    color: "#fe3aff",
  },
];


export const top = [
  {
    id: 1,
    image: "./manga/top-01.webp",
    number: "1",
    name: "Амттай цус",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "36",
    color: "#ff80bd",
  },
  {
    id: 2,
    image: "./manga/top-02.webp",
    number: "2",
    name: "Алуурчин",
    rating: "5/5",
    category: "Тулаант",
    views: "28",
    color: "#80a3ea",
  },
  {
    id: 3,
    image: "./manga/top-03.webp",
    number: "3",
    name: "Миний хайрт хань",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
];

export const reading = [
  {
    id: 1,
    image: "./manga/reading-01.webp",
    name: "Тэнгэрлэгийг цуглуулах",
    rating: "5/5",
    category: "Ер бусын",
    views: "36",
    color: "#37a5b3",
  },
  {
    id: 2,
    image: "./manga/reading-02.webp",
    name: "Бид амархан үхэхгүй!",
    rating: "5/5",
    category: "Адал явдал",
    views: "28",
    color: "#80a3ea",
  },
  {
    id: 3,
    image: "./manga/reading-03.webp",
    name: "Хязгааргүй байдал",
    rating: "5/5",
    category: "Триллер",
    views: "28",
    color: "#80a3ea",
  },
  {
    id: 4,
    image: "./manga/reading-04.webp",
    name: "Нэг дэлхий. Нэг тулаан.",
    rating: "5/5",
    category: "Жүжиг",
    views: "28",
    color: "#97c256",
  },
];

export const recent = [
  {
    id: 1,
    image: "./manga/recent-01.webp",
    name: "Тэнгэрлэгийг цуглуулах",
    category: "Ер бусын",
    views: "36",
    color: "#37a5b3",
  },
  {
    id: 2,
    image: "./manga/recent-02.webp",
    name: "Бид амархан үхэхгүй!",
    rating: "5/5",
    category: "Адал явдал",
    views: "28",
    color: "#fff15c",
  },
  {
    id: 3,
    image: "./manga/recent-03.webp",
    name: "Хязгааргүй байдал",
    rating: "5/5",
    category: "Триллер",
    views: "28",
    color: "#ff80bd",
  },
  {
    id: 4,
    image: "./manga/recent-04.webp",
    name: "Чамтай өнгөрөөсөн сайхан цаг минь",
    rating: "5/5",
    category: "Жүжиг",
    views: "28",
    color: "#9cabc4",
  },
  {
    id: 5,
    image: "./manga/recent-05.webp",
    name: "Миний хайрт хань",
    rating: "5/5",
    category: "Драма",
    views: "28",
    color: "#97c256",
  },
  {
    id: 6,
    image: "./manga/recent-06.webp",
    name: "Нэг дэлхий. Нэг тулаан.",
    rating: "5/5",
    category: "Хүчирхэг",
    views: "28",
    color: "#8ae5de",
  },
];