export const all = [
  {
    id: 1,
    image: "./manga/all-33.webp",
    name: "Агуу зүйл бүтээх зам",
    rating: "5/5",
    category: "Адал явдал",
    views: "36",
    color: "#80a3ea",
  },
  {
    id: 2,
    image: "./manga/all-32.webp",
    name: "Хаалттай хот",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "28",
    color: "#f12867",
  },
  {
    id: 3,
    image: "./manga/all-31.webp",
    name: "Эзэнт гүрний сэнтий",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
  {
    id: 4,
    image: "./manga/all-30.webp",
    name: "Тоглоом дахин давтагдана",
    rating: "5/5",
    category: "Хүчтэн",
    views: "44",
    color: "#37a5b3",
  },
  {
    id: 5,
    image: "./manga/all-29.webp",
    name: "Хамгийн агуу зүйл",
    rating: "5/5",
    category: "Уран зөгнөл",
    views: "44",
    color: "#ff80bd",
  },
  {
    id: 6,
    image: "./manga/all-28.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
  {
    id: 7,
    image: "./manga/all-27.webp",
    name: "Агуу зүйл бүтээх зам",
    rating: "5/5",
    category: "Адал явдал",
    views: "36",
    color: "#80a3ea",
  },
  {
    id: 8,
    image: "./manga/all-26.webp",
    name: "Хаалттай хот",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "28",
    color: "#f12867",
  },
  {
    id: 9,
    image: "./manga/all-25.webp",
    name: "Эзэнт гүрний сэнтий",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
  {
    id: 10,
    image: "./manga/all-24.webp",
    name: "Тоглоом дахин давтагдана",
    rating: "5/5",
    category: "Хүчтэн",
    views: "44",
    color: "#37a5b3",
  },
  {
    id: 11,
    image: "./manga/all-23.webp",
    name: "Хамгийн агуу зүйл",
    rating: "5/5",
    category: "Уран зөгнөл",
    views: "44",
    color: "#ff80bd",
  },
  {
    id: 12,
    image: "./manga/all-22.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
  {
    id: 13,
    image: "./manga/all-21.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
  {
    id: 14,
    image: "./manga/all-20.webp",
    name: "Агуу зүйл бүтээх зам",
    rating: "5/5",
    category: "Адал явдал",
    views: "36",
    color: "#80a3ea",
  },
  {
    id: 16,
    image: "./manga/all-19.webp",
    name: "Хаалттай хот",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "28",
    color: "#f12867",
  },
  {
    id: 15,
    image: "./manga/all-18.webp",
    name: "Эзэнт гүрний сэнтий",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
  {
    id: 17,
    image: "./manga/all-17.webp",
    name: "Тоглоом дахин давтагдана",
    rating: "5/5",
    category: "Хүчтэн",
    views: "44",
    color: "#37a5b3",
  },
  {
    id: 18,
    image: "./manga/all-16.webp",
    name: "Хамгийн агуу зүйл",
    rating: "5/5",
    category: "Уран зөгнөл",
    views: "44",
    color: "#ff80bd",
  },
  {
    id: 19,
    image: "./manga/all-15.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
  {
    id: 20,
    image: "./manga/all-14.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
  {
    id: 21,
    image: "./manga/all-13.webp",
    name: "Агуу зүйл бүтээх зам",
    rating: "5/5",
    category: "Адал явдал",
    views: "36",
    color: "#80a3ea",
  },
  {
    id: 22,
    image: "./manga/all-12.webp",
    name: "Хаалттай хот",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "28",
    color: "#f12867",
  },
  {
    id: 23,
    image: "./manga/all-11.webp",
    name: "Эзэнт гүрний сэнтий",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
  {
    id: 24,
    image: "./manga/all-10.webp",
    name: "Тоглоом дахин давтагдана",
    rating: "5/5",
    category: "Хүчтэн",
    views: "44",
    color: "#37a5b3",
  },
  {
    id: 25,
    image: "./manga/all-09.webp",
    name: "Хамгийн агуу зүйл",
    rating: "5/5",
    category: "Уран зөгнөл",
    views: "44",
    color: "#ff80bd",
  },
  {
    id: 26,
    image: "./manga/all-08.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
  {
    id: 27,
    image: "./manga/all-07.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
  {
    id: 28,
    image: "./manga/all-06.webp",
    name: "Агуу зүйл бүтээх зам",
    rating: "5/5",
    category: "Адал явдал",
    views: "36",
    color: "#80a3ea",
  },
  {
    id: 29,
    image: "./manga/all-05.webp",
    name: "Хаалттай хот",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "28",
    color: "#f12867",
  },
  {
    id: 30,
    image: "./manga/all-04.webp",
    name: "Эзэнт гүрний сэнтий",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
  {
    id: 31,
    image: "./manga/all-04.webp",
    name: "Тоглоом дахин давтагдана",
    rating: "5/5",
    category: "Хүчтэн",
    views: "44",
    color: "#37a5b3",
  },
  {
    id: 32,
    image: "./manga/all-03.webp",
    name: "Хамгийн агуу зүйл",
    rating: "5/5",
    category: "Уран зөгнөл",
    views: "44",
    color: "#ff80bd",
  },
  {
    id: 33,
    image: "./manga/all-02.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
  {
    id: 33,
    image: "./manga/all-01.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
];

export const popular = [
  {
    id: 1,
    image: "./manga/popular-01.webp",
    name: "Агуу зүйл бүтээх зам",
    rating: "5/5",
    category: "Адал явдал",
    views: "36",
    color: "#80a3ea",
  },
  {
    id: 2,
    image: "./manga/popular-02.webp",
    name: "Хаалттай хот",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "28",
    color: "#f12867",
  },
  {
    id: 3,
    image: "./manga/popular-07.webp",
    name: "Эзэнт гүрний сэнтий",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
  {
    id: 4,
    image: "./manga/popular-08.webp",
    name: "Тоглоом дахин давтагдана",
    rating: "5/5",
    category: "Хүчтэн",
    views: "44",
    color: "#37a5b3",
  },
  {
    id: 5,
    image: "./manga/popular-05.webp",
    name: "Хамгийн агуу зүйл",
    rating: "5/5",
    category: "Уран зөгнөл",
    views: "44",
    color: "#ff80bd",
  },
  {
    id: 6,
    image: "./manga/popular-06.webp",
    name: "Алдагдсан ертөнц",
    rating: "5/5",
    category: "Драма",
    views: "44",
    color: "#97c256",
  },
];


export const something = [
  {
    id: 1,
    image: "/manga/something-01.webp",
    name: "Шидэт сарнай",
    rating: "5/5",
    category: "Адал явдал",
    views: "36",
    color: "#80a3ea",
  },
  {
    id: 2,
    image: "/manga/something-02.webp",
    name: "Миний таван нэрт дайчдын түүх",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "28",
    color: "#f12867",
  },
  {
    id: 3,
    image: "/manga/something-03.webp",
    name: "Ичгүүргүй илбэчин",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
  {
    id: 4,
    image: "/manga/something-04.webp",
    name: "Тоглоом дахин давтагдана",
    rating: "5/5",
    category: "Хүчтэн",
    views: "44",
    color: "#37a5b3",
  },
  {
    id: 5,
    image: "/manga/something-05.webp",
    name: "Хөрөнгө оруулагч Z! Нөлөөлөл",
    rating: "5/5",
    category: "Тулаант",
    views: "32",
    color: "#54cf17",
  },
  {
    id: 6,
    image: "/manga/something-06.webp",
    name: "Чамтай өнгөрөөсөн сайхан цаг минь",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "26",
    color: "#fe3aff",
  },
  {
    id: 7,
    image: "/manga/all-07.webp",
    name: "Дайны хөтөч",
    rating: "5/5",
    category: "Агуу хүчтэн",
    views: "32",
    color: "#80a3ea",
  },
  {
    id: 8,
    image: "/manga/all-06.webp",
    name: "Агуу шидийн эрэлд",
    rating: "5/5",
    category: "Тулаант",
    views: "26",
    color: "#37a5b3",
  },
];


export const top = [
  {
    id: 1,
    image: "./manga/top-01.webp",
    number: "1",
    name: "Амттай цус",
    rating: "5/5",
    category: "Хайр дурлал",
    views: "36",
    color: "#ff80bd",
  },
  {
    id: 2,
    image: "./manga/top-02.webp",
    number: "2",
    name: "Алуурчин",
    rating: "5/5",
    category: "Тулаант",
    views: "28",
    color: "#80a3ea",
  },
  {
    id: 3,
    image: "./manga/top-03.webp",
    number: "3",
    name: "Миний хайрт хань",
    rating: "5/5",
    category: "Романтик",
    views: "41",
    color: "#f1de15",
  },
  {
    id: 4,
    image: "./manga/interest-06.webp",
    number: "4",
    name: "Амттай цус",
    rating: "5/5",
    category: "Шидтэн",
    views: "36",
    color: "#97c256",
  },
  {
    id: 5,
    image: "./manga/interest-05.webp",
    number: "5",
    name: "Алуурчин",
    rating: "5/5",
    category: "Хар хүч",
    views: "28",
    color: "#37a5b3",
  },
  {
    id: 6,
    image: "./manga/interest-03.webp",
    number: "6",
    name: "Миний хайрт хань",
    rating: "5/5",
    category: "Алуурчин",
    views: "41",
    color: "#9cabc4",
  },
];

export const reading = [
  {
    id: 1,
    image: "./manga/reading-01.webp",
    name: "Тэнгэрлэгийг цуглуулах",
    rating: "5/5",
    category: "Ер бусын",
    views: "36",
    color: "#37a5b3",
  },
  {
    id: 2,
    image: "./manga/reading-02.webp",
    name: "Бид амархан үхэхгүй!",
    rating: "5/5",
    category: "Адал явдал",
    views: "28",
    color: "#80a3ea",
  },
  {
    id: 3,
    image: "./manga/reading-03.webp",
    name: "Хязгааргүй байдал",
    rating: "5/5",
    category: "Триллер",
    views: "28",
    color: "#80a3ea",
  },
  {
    id: 4,
    image: "./manga/reading-04.webp",
    name: "Нэг дэлхий. Нэг тулаан.",
    rating: "5/5",
    category: "Жүжиг",
    views: "28",
    color: "#97c256",
  },
];

export const save = [
  {
    id: 1,
    image: "./manga/recent-08.webp",
    name: "Хүчирхэг хүмүүсийн нэгдэл",
    rating: "5/5",
    category: "Ер бусын",
    more: "1-р бүлэг",
    views: "36",
    color: "#37a5b3",
  },
  {
    id: 2,
    image: "./manga/recent-07.webp",
    name: "Эмч гэж бодоо юу?",
    rating: "5/5",
    category: "Адал явдал",
    more: "2-р бүлэг",
    views: "28",
    color: "#80a3ea",
  },
];

export const recent = [
  {
    id: 1,
    image: "./manga/recent-01.webp",
    name: "Тэнгэрлэгийг цуглуулах",
    category: "Ер бусын",
    more: "1-р бүлэг",
    views: "36",
    color: "#37a5b3",
  },
  {
    id: 2,
    image: "./manga/recent-02.webp",
    name: "Бид амархан үхэхгүй!",
    rating: "5/5",
    category: "Адал явдал",
    more: "2-р бүлэг",
    views: "28",
    color: "#fff15c",
  },
  {
    id: 3,
    image: "./manga/recent-03.webp",
    name: "Хязгааргүй байдал",
    rating: "5/5",
    category: "Триллер",
    more: "3-р бүлэг",
    views: "28",
    color: "#ff80bd",
  },
  {
    id: 4,
    image: "./manga/recent-04.webp",
    name: "Чамтай өнгөрөөсөн сайхан цаг минь",
    rating: "5/5",
    category: "Жүжиг",
    more: "4-р бүлэг",
    views: "28",
    color: "#9cabc4",
  },
  {
    id: 5,
    image: "./manga/recent-05.webp",
    name: "Миний хайрт хань",
    rating: "5/5",
    category: "Драма",
    more: "5-р бүлэг",
    views: "28",
    color: "#97c256",
  },
  {
    id: 6,
    image: "./manga/recent-06.webp",
    name: "Нэг дэлхий. Нэг тулаан.",
    rating: "5/5",
    category: "Хүчирхэг",
    more: "6-р бүлэг",
    views: "28",
    color: "#8ae5de",
  },
];